exec-once = waybar
exec-once = hyprsunset
exec-once = hypridle
exec-once = hyprpaper
exec-once = swayosd-server
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

