# Playback Control
SPACE       cycle pause          # Spacebar to Pause / Play
p           cycle pause          # Alternative Pause / Play
q           quit                 # Quit player
ESC         set fullscreen no    # Exit fullscreen
f           cycle fullscreen     # Toggle fullscreen

# Seeking & Navigation
RIGHT       seek 5               # Skip forward 5 seconds
LEFT        seek -5              # Skip backward 5 seconds
Shift+RIGHT seek 30              # Skip forward 30 seconds
Shift+LEFT  seek -30             # Skip backward 30 seconds
h           seek -5
l           seek 5
H           seek -30
L           seek 30

# Previous / next episode or song
j           playlist-prev
k           playlist-next
UP          playlist-prev
DOWN        playlist-next

# Playback speed
[           add speed -0.1
]           add speed 0.1
\           set speed 1

# Volume
-           add volume -5
=           add volume 5
m           cycle mute

# Subtitles
s           cycle sub

# Audio
a           cycle audio

# Screenshot
S           screenshot


# Clear/Ignore annoying defaults (like single number keys)
1           ignore
2           ignore
3           ignore
4           ignore
5           ignore
6           ignore
7           ignore
8           ignore
