[main]

# Font
font=CaskaydiaMono Nerd Font:size=16

# Terminal used for launching terminal applications
terminal=foot

# Layout
width=32
lines=10

horizontal-pad=15
vertical-pad=10
inner-pad=10

line-height=32

# Window
border-width=2
border-radius=10

dpi-aware=auto

# Prompt
prompt=" > "


# ============================================================================
# COLORS
# Official Omarchy Matte Black palette
# ============================================================================

[colors]

# Main background
background=121212ff

# Normal text
text=bebebeff

# Matching text
match=e68e0dff

# Selected row
selection=333333ff

# Text of selected row
selection-text=eaeaeaff

# Border
border=8a8a8d80


# ============================================================================
# BORDER
# ============================================================================

[border]

width=2
radius=10
selection-radius=10


# ============================================================================
# DMENU
# ============================================================================

[dmenu]

exit-immediately-if-empty=no
