general {
    lock_cmd = pidof hyprlock || hyprlock # lock screen
    before_sleep_cmd = pidof hyprlock || hyprlock # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on # to avoid having to press a key twice to turn on the display.
    inhibit_sleep = 5 # wait until screen is locked
}

listener {
    timeout = 300                      # 5min
    on-timeout = pidof hyprlock || hyprlock # lock screen when timeout has passed
}

listener {
    timeout = 240                      # 4min
    on-timeout = hyprctl dispatch dpms off # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen on when activity is detected
}

listener {
    timeout = 360                      # 6min
    on-timeout = systemctl suspend # suspend system when timeout has passed
}

listener {
    timeout = 60                       # 1min
    on-timeout = brightnessctl -sd platform::kbd_backlight set 0
    on-resume = brightnessctl -rd platform::kbd_backlight
}
