general {
    ignore_empty_input = true
}

background {
    monitor =
    color = rgba(12,12,12,0.1)
    path = ~/.config/hypr/backgrounds/background.jpg
    blur_passes = 2
}

animations {
    enabled = false
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(204, 204, 204, 1)
    font_size = 120
    font_family = SF Pro Display Bold
    position = 0, 350
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %d %B")"
    color = rgba(204, 204, 204, 1)
    font_size = 17
    font_family = SF Pro Display Bold
    position = 0, 250
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    position = 0, -450
    halign = center
    valign = center

    inner_color = rgba(25, 25, 25, 1)
    outer_color = rgba(35, 35, 35, 1)
    outline_thickness = 3

    font_family = CaskaydiaMono Nerd Font
    font_color = rgba(204, 204, 204, 1)
    placeholder_text = Enter Password
    check_color = rgba(245,158,11,1.0)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 10
    fade_on_empty = false
    
    #shadows
    shadow_passes = 1
    shadow_range = 15
    shadow_render_power = 4
    shadow_color = rgba(17, 17, 17, 1)
}

auth {
    fingerprint:enabled = true
}
