$background = rgb(121212)
$foreground = rgb(bebebe)
$foreground_bright = rgb(eaeaea)
$surface = rgb(333333)
$selection = rgb(515151)
$muted = rgb(8a8a8d)
$accent = rgb(e68e0d)
$accent_bright = rgb(f59e0b)
$error = rgb(d35f5f)
$error_dark = rgb(b91c1c)
$warning = rgb(ffc107)
$shadow = rgba(18, 18, 18, 0.88)

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = rgba(18, 18, 18, 0.10)
    path = ~/Pictures/backgrounds/background.png
    blur_passes = 2
}

animations {
    enabled = false
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = $foreground
    font_size = 120
    font_family = SF Pro Display Bold
    position = 0, 350
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %d %B")"
    color = $foreground
    font_size = 17
    font_family = SF Pro Display Bold
    position = 0, 250
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 50
    position = 0, -400
    halign = center
    valign = center
    inner_color = $background
    outer_color = $surface
    outline_thickness = 2
    font_family = CaskaydiaMono Nerd Font
    font_color = $foreground
    placeholder_text = Enter Password
    check_color = $accent
    fail_color = $error
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    rounding = 10
    fade_on_empty = false
    shadow_passes = 2
    shadow_range = 15
    shadow_render_power = 2
    shadow_color = $shadow
}

auth {
    fingerprint:enabled = true
}
