# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#bebebe"

# Title color for boxes
theme[title]="#8a8a8d"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e68e0d"

# Background color of selected item in processes box
theme[selected_bg]="#222222"

# Foreground color of selected item in processes box
theme[selected_fg]="#e68e0d"

# Color of inactive/disabled text
theme[inactive_fg]="#333333"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#8a8a8d"

# Cpu box outline color
theme[cpu_box]="#8a8a8d"

# Memory/disks box outline color
theme[mem_box]="#8a8a8d"

# Net up/down box outline color
theme[net_box]="#8a8a8d"

# Processes box outline color
theme[proc_box]="#8a8a8d"

# Box divider line and small boxes line color
theme[div_line]="#8a8a8d"

# Temperature graph colors
theme[temp_start]="#8a8a8d"
theme[temp_mid]="#e68e0d"
theme[temp_end]="#b91c1c"

# CPU graph colors
theme[cpu_start]="#8a8a8d"
theme[cpu_mid]="#e68e0d"
theme[cpu_end]="#b91c1c"

# Mem/Disk free meter
theme[free_start]="#8a8a8d"
theme[free_mid]="#e68e0d"
theme[free_end]="#b91c1c"

# Mem/Disk cached meter
theme[cached_start]="#8a8a8d"
theme[cached_mid]="#e68e0d"
theme[cached_end]="#b91c1c"

# Mem/Disk available meter
theme[available_start]="#8a8a8d"
theme[available_mid]="#e68e0d"
theme[available_end]="#b91c1c"

# Mem/Disk used meter
theme[used_start]="#8a8a8d"
theme[used_mid]="#e68e0d"
theme[used_end]="#b91c1c"

# Download graph colors
theme[download_start]="#8a8a8d"
theme[download_mid]="#e68e0d"
theme[download_end]="#b91c1c"

# Upload graph colors
theme[upload_start]="#8a8a8d"
theme[upload_mid]="#e68e0d"
theme[upload_end]="#b91c1c"
