[mgr]
ratio = [2, 5, 5]
linemode = "mtime"
scrolloff = 10

[preview]
max_width = 2048
max_height = 2048
image_delay = 0
tab_size = 2
image_quality = 70

[opener]
edit = [
  { run = 'nvim %s', desc = "Edit with Neovim", block = true, for = "unix" },
]

play = [
  { run = 'mpv --force-window %s', desc = "Play with mpv", orphan = true, for = "unix" },
]

pdf = [
  { run = 'zathura %s', desc = "Open PDF with Zathura", orphan = true, for = "unix" },
]

image = [
  { run = 'imv-dir %s', desc = "Open with imv-dir", orphan = true, for = "unix" },
]

open = [
  { run = 'xdg-open %s', desc = "Open with system default", for = "linux" },
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "application/pdf", use = "pdf" },
  { mime = "audio/*", use = "play" },
  { mime = "video/*", use = "play" },
  { mime = "image/*", use = "image" },
  { url = "*", use = "open" },
]

prepend_rules = [
	{ url = "*.json", use = "edit" },

	{ url = "*.html", use = [ "open", "edit" ] },
]
