#Reload tmux.conf
unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

#Set the leader key to Ctrl+s
unbind C-b
set-option -g prefix C-x
bind-key C-x send-prefix

#Set window and pane index to 1
set -g base-index 1
set -g pane-base-index 1

#Enable mouse-mode
set -g mouse on

#Set vi-mode movement keybinding
set-window-option -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

set-option -g focus-events on

#Manage resurrect-continuum sessions
set -g @continuum-restore 'on'
set -g @continuum-boot 'on'
set -g @continuum-save-interval '10'
set -g @resurrect-processes 'btop yazi'

#Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'

#Run tpm ---> always at the bottom
run '~/.tmux/plugins/tpm/tpm'
